### ISSUE TITLE
[Question] Dune2 - armor 

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/d2#11]
@Nyerguds : did armor not exist in dune2 ? ... while studying your .ini-dumps i could not find any values so far , indicating any armor on vehicles or buildings

edit : 
another question ... can a sandworm actually eat a devastator ? ... cause the rules tell me that a sandworm-attack does actually 300 damage ... but a devastator has 400 hp

**Comment by Nyerguds** [comment]
I don't think there's armor in Dune II, no.Though MrFlibble or TrueBrain or Dynasty might know more about that; they've done a lot more research into Dune II than I have.

Fairly sure I've seen Devastators eaten, yes. Whatever damage is set on the Sandworm is mostly likely ignored in favour of the special logic they have to eat stuff. Do note, according to Dune's internal rules, Sandworms can only eat 3 things before they vanish automatically.

Oh, interesting note on that... when fiddling around with that, and making sandworms not disappear from eating units, we noticed that in Dune II's earlier missions, sandworms are often set to Area Guard instead of Ambush. This means you don't get the scary "attack everything" logic, but we found out that it makes the sandworm a lot more unpredictable and fun: rather than the classic "discover worm, pull everything back on concrete, kill worm", you had worms that might be aggressive, might be docile, and might change that behaviour during gameplay. A docile worm might change to aggressive when attacked, or just randomly. It was great fun to have them that way, since they lasted a lot further into the games, and attacking a docile one was not just eliminating a potential risk, but also held the risk of _making_ it aggressive :)

**Comment by Micr0Bit** [comment]
@Nyerguds : i saw on fed2k that you auctioned an original box of dune2 for dos ... did actually try them on a computer already ? if so ... can you recommend a machine / laptop to play the originals ? 

a "compaq lte" could be a good idea ... according to https://www.youtube.com/watch?v=k2v7k-wAm2E

problem though ... i rarely find any of those on ebay ... so i thought you might have an alternative solution , since you already own the game itself

**Comment by Nyerguds** [comment]
I already collected all installer files of all versions of Dune II, so I never saw a need to check the disks. I mostly wanted it for the clean cover image.

As for playing the original... well, I'd recommend either DOSBox, or the aforementioned Dune Dynasty. Given the fact Dynasty is not a clone, but actually built on the reverse-engineered source code from the OpenDune project, it acts exactly like the original, aside from its UI upgrades.

*Dune Dynasty info*
Official page:
http://dunedynasty.sourceforge.net/
My own installation/tweaking guide:
https://forum.dune2k.com/topic/24316-dune-dynasty/?page=12#comment-391240
Some hints on the resolution settings:
https://forums.cncnet.org/index.php?topic=6176.msg45369#msg45369

**Comment by Micr0Bit** [comment]
yeah , i know all those options ... im constantly firing dune2 in dosbox up .. to check behaviour of units , check values ,gameplay and so on ... 

the thing is , i dont trust emulations (dosbox) 100% ... in terms of speed ... because different cpus might have a different effect on the gameplay or am i wrong ? 
i know i could just play around in the dosbox-settings ... but having a 100% the same experience as a Dune2 - player in the 90s ... is only given when you actually use a machine from that era 

anyway , for the dune2 -> openra translation ... dosbox will do the job
