### ISSUE TITLE
Bug list and youtube testing videos

### ISSUE THREAD

**Issue by Blakeley00** [OpenRA/d2#50]
Hi guys,

I love the awesome work you're doing and am amazed there's nothing out there showing off your work so I decided to do some videos to get more people aware of your project. Had a lot of trouble getting the mod working a couple of months back but Micr0bit found my RA2 mod video talking about our D2 problems and helped us out so the videos are done!

We had a few problems which I'll list below (all can be found in 1 or both of the videos below if you're not sure about anything I've said). This was about 2-3mths ago now so it's possible some are already fixed in your latest version. Also some of these issues may be out of your control, and no doubt you're probably already aware of most of these anyway lol. :)

**Bugs/Issues:**
- No music & minimal sounds (convert midis to mp3s?)
- Can't space out buildings, in original D2 you could if you built out the concrete.
- Production buildings get stuck on 'ready' and cannot produce more units when there are other buildings too close (caused by above issue) even when there is still ample space left over outside the rest of produce building.
- Buildings are too weak, most units can destroy them in a few shots.
- Combat tanks are super duper artillery firing death tanks from HELL. They can 1 shot kill nearly everything lol!! Humans, tanks, buildings.. they're crazy strong lol!
- Siege tanks were stronger short range combat tanks in original D2, they were weakened long range artillery in D2K, your Siege are still behaving like their D2K counterparts.
- Super weapons are recharging every 30 seconds! (is that just for testing purposes?)
- Devastator can recharge health super quick.
- Carryalls get stuck and just sit there until their host faction dies.
- Scores don't work
- Some sort of graphics scaling option? Everything is so small due to D2's art assets being so low rez. A 2x scaler option in the settings would be brilliant.
- Any plans to add the awesome sub factions (Sardukar, Fremen & Mercs)?

**Videos:**
3 Player match test game
[https://www.youtube.com/watch?v=VW3w_qHs3XI](https://www.youtube.com/watch?v=VW3w_qHs3XI)

Single player skirmish test game
[https://www.youtube.com/watch?v=BVswMcT69h0](https://www.youtube.com/watch?v=BVswMcT69h0)

**Comment by Micr0Bit** [comment]
Hey @Blakeley00 , you and your friends are awesome , thank you very much for testing and for the recordings on youtube (dune2 really needs that)
the progress/development/testing is really slow compared to other mods ... i hope it wasnt too much of a pain for you guys to play this ... 

its pretty much a construction area in a desert

to your questions :
>No music & minimal sounds (convert midis to mp3s?)
yes theres a few sound-problems and music doesnt work yet ... theres one bug-ticket for unit-sounds #36 
>Can't space out buildings, in original D2 you could if you built out the concrete.
we just recently implemented the "original" basebuilding and concrete-placement ... it exactly works like the original and when you download and play the latest master you should be good to go , for details checkout #9 
>Production buildings get stuck on 'ready' and cannot produce more units when there are other buildings too close (caused by above issue) even when there is still ample space left over outside the rest of produce building.
This is a known problem , all structures need more entrances ... "AND" something called an "emergency carryall" ... once a production building is completely blocked off , a neutral carryall will appear and carry the unit the stuck out to the next free cell , see #43 , #44 
>Buildings are too weak, most units can destroy them in a few shots.
Combat tanks are super duper artillery firing death tanks from HELL. They can 1 shot kill nearly everything lol!! Humans, tanks, buildings.. they're crazy strong lol!
Siege tanks were stronger short range combat tanks in original D2, they were weakened long range artillery in D2K, your Siege are still behaving like their D2K counterparts.
Super weapons are recharging every 30 seconds! (is that just for testing purposes?)
Devastator can recharge health super quick.
#17 
>Carryalls get stuck and just sit there until their host faction dies.
What do mean with "just sit there" ?
>Scores don't work
The Score for D2 in general needs an ovehaul because it works a bit different then our score-system for all mods ... but yeah , we should make this work until we have the original solution (this might me low priority though)
>Some sort of graphics scaling option? Everything is so small due to D2's art assets being so low rez. A 2x scaler option in the settings would be brilliant.
The game should already zoom in on default when you are starting the mod (somethow that doesnt work everytime) ... you can zoom in with "." while ingame (or mousewheel + ctrl)
A 2x scaler would be neat though , as it would mimic the 320x240 resoultion from the original

**Comment by Blakeley00** [comment]
No worries man. Glad I could help! Hopefully the videos bring you more support. I'm gonna post them in a few dune forums & facebook groups too. :)

> What do mean with "just sit there" ?
Yeah I discovered the carryall issue towards the end of the second video, my skirmish game. Here's a link to the exact moment where I notice that the Ordos carryalls and my carryalls are sitting on the ground and not flying anywhere picking up harvesters:
[https://youtu.be/BVswMcT69h0?t=31m10s](https://youtu.be/BVswMcT69h0?t=31m10s)

> The game should already zoom in on default when you are starting the mod (somehow that doesnt always work) ... you can zoom in with "." while ingame (or mousewheel + ctrl)
Oh wow.. thanks heaps for that. I'll make a note of that in my video descriptions as I wish I'd known that before filming them haha. Figured there was some openra zoom shortcut but I just didn't know it. And yeah it didn't automatically work for us sadly.

**Comment by Micr0Bit** [comment]
>What do mean with "just sit there" ?
Yeah I discovered the carryall issue towards the end of the second video, my skirmish game. Here's a link to the exact moment where I notice that the Ordos carryalls and my carryalls are sitting on the ground and not flying anywhere picking up harvesters:
https://youtu.be/BVswMcT69h0?t=31m10s

yeah thats a bug , i've made a ticket for that one #51
