### ISSUE TITLE
sharing some Dune2theGoldenPath resources

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/d2#87]
Hey,
dderevjanik created some custom terrain tiles #86.
Drackbolt did kinda the same thing for the d2tgp project.
He once gave me some spritesheets, but the terrain tiles wasn't include. I just checked them :(
So I tried to contact Drackbolt today to asked for the sprites. I don't have an aswer yet, but I'm confident,that he will share them.

Anyway here is that file Drackbold gave me. It contains buildings, explosions, sounds, units. 
custom stuff like: the mtp, the v2like deathhand, flaktrike, raider (2wheels),... )
[D2TGP_resources.zip]()

**Comment by evgeniysergeev** [comment]
It's d2 mod not golden path mod. It will have some enhancements but I don't like to add a lot of such stuff. And I don't think that including assets in bmp format is a legal.

**Comment by evgeniysergeev** [comment]
d2 mod should be VERY close to original game. some enhancements possible but not in assets. not in sounds or images. this was original idea of d2 mod

**Comment by TheRaffy** [comment]
Get me, I don't wanna split the d2 community, any d2 mod is better than nothing. 
I just shared the bmp's cause i only have them in that format.
My idea was that somebody who maybe likes to add additional units (like the custom units of tgp) can take them an convert them to shps files and use them inside his custom maps. I don't like to see that bmp's files to be used directly, neither do they need be any part of the d2 mod. There are a lot maps for RA for example that bring new units or other stuff with them.

**Comment by dderevjanik** [comment]
@evgeniysergeev what does "VERY close to original game" means to you ? Don't get me wrong, I just want to understand, which direction are you going with d2 mod. 

Because, honestly, I don't want to play original d2 again, it has outdated strategic mechanics. I want to play d2 again and had similar mechanics like games today with plenty features. I want to play d2 with my friends over internet and have fun time. If I want to play original d2 (maybe for nostalgic reason), I can use dosbox with original d2.  

But we are here, an open source community, which leads a direction and can improve gameplay of old game based on feedback from community. We have that "power" to improve old game, add new gameplay mechanics, fix bugs, improve balance, focus on MP, add plenty of new maps (and of curse, tilesets :D ) and that's what I'm looking for. 

I can see @TheRaffy point of view to revive community behind DTGP and continue where it ended. DTGP and this d2 mod sharing same playerbase and thanks to campaign, it can expand much more. There are already several d2 clones with improved gameplay, new graphics, new mechanics, new campaigns, etc... Why we should not use this opportunity to improve grandpa of strategy games ? 

You are the main contributor and I would like to know, what are your plan with d2. Maybe, we can help you to fulfill them .

Again, don't get me wrong with this comments, I just want to share my point of view. I really appreciate your, MustphaTR, Micr0bit and others work. Thank you very much guys for bringing old game alive !

**Comment by evgeniysergeev** [comment]
edited for remove possible copyrighted assets from here
