### ISSUE TITLE
Establish original concrete and structure placement

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/d2#9]
As long as there is a building or slab attached in any direction ... players should be allowed to place a building or a slab for as far as the rock goes ... 

Only sand or the enemies slabs/buildings should be able to stop a basecreep.

@Nyerguds : please correct me if im wrong here

**Comment by Nyerguds** [comment]
Nope, that's spot on; concrete served as way to spread out the base. In C&C they replaced this by bibs, in RA they kept the bibs but added build radius, and in later games they removed the bibs altogether and just stuck to the build radius mechanism.

Enemy slabs prevent expansion by slabs, but you _can_ perfectly build on them as if they were yours.

Heck, in Warcraft 1 you don't actually build a "base" but a "village"; instead of concrete, you have to build road, and can only build structures connected to those roads. That was a pretty fun mechanic, actually. The beta shots and graphics I found actually showed they considered doing something like that in C&C1, before they went with the final "bibs" idea.

**Comment by evgeniysergeev** [comment]
bef1b7e3a7318176c44a2eff12b18496b29c4f04

**Comment by Micr0Bit** [comment]
@evgeniysergeev : i see you fixed problem with concrete ... great job ... we now have the "original" base-expansion ... awesome

**Comment by Micr0Bit** [comment]
i was pretty sure that this was fixed at some point ... i dont understand why this doesnt work anymore .. placing x1 slabs one after another

**Comment by evgeniysergeev** [comment]
It was never working. concrete slabs modify terrain layer and removed after placement and there no way to keep it. if it not removed, it do not allow to place building over concrete or do not allow to walk units on it.

**Comment by Micr0Bit** [comment]
still , in a previous version ... i could place x1-slabs in a 3-cell radius around every placed building (+ placed conyard) which was atleast a solution for the time ...  but now i can place 1x-slabs only in a 1-cell radius around the placed conyard and thats it  ... you have changed that somehow on the new d2.oramod

if you dont understand what i mean , or you forgot how you did that ... i can link you the ora.zip with this solution

**Comment by evgeniysergeev** [comment]
Did you test ability to place buildings on the concrete slabs in this solution?

**Comment by Micr0Bit** [comment]
yeah , and that works 

https://www.dropbox.com/s/174lrv5vyirs9gq/OpenRA-d2.zip?dl=0

**Comment by Micr0Bit** [comment]
@abcdefg30 : please a "Feature"-tag instead of "Bug"

**Comment by evgeniysergeev** [comment]
Then #13266 will be done, this changes will add original buildings placement: 
[issue_9.zip](https://github.com/OpenRA/d2/files/1033785/issue_9.zip)
while #13266 not fixed, it’s possible to modify one line in Building.cs to be able to build using this changes:
[issue_9_building_cs.diff.txt](https://github.com/OpenRA/d2/files/1033786/issue_9_building_cs.diff.txt)

**Comment by Micr0Bit** [comment]
this seems to fixed with 6f05e2f
